
services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres
    
  distribuitedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Microservices/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
     
