
services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres
    
  distribuitedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messageBroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Microservices/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Microservices/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Microservices/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Microservices/Ordering/Ordering.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
     



